CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, 
  username TEXT,
  password TEXT
)

CREATE TABLE Nodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, 
  ip TEXT,
  domain TEXT
)